### ISSUE TITLE
Produce a TL;DR version

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#7] opened 2019-02-25 03:24 UTC
"Thanks for sending it over. 
yeah i took a look at it. I think in general, such a framework definitely make sense."
"There are also good examples on the applications of it. But they are pretty lengthy. Would be good to provide like a TL;DR of it"

**Comment by colourful-land** [comment] 2019-03-03 03:29
Refer to my recent draft article as an attempt to produce an easy read.
[book-token-as-an-example.pdf](https://github.com/AlphaWallet/TBML/files/2922720/book-token-as-an-example.pdf)

**Comment by colourful-land** [comment] 2019-03-03 03:57
Like always, @James-Sangalli sneered at the 6-page long book token story without producing a good one himself. He thinks that it's easier to tell the story by explaining that blockchain integrates services.
Following that thinking here is another attempt (unfinished).

== Blockchain allows integrated user experience ==

A smartphone is not smart.

If it is really smart, you should be able to ask "show me how much money do I have", it should summarise your balance over the three banks you have an account with, minus the credit card debts, tell you the final result in a number. 

If really smart, when you go to a layby counter to pick up an online order, your smartphone should give you the order ID without you rummage through your emails. It should be able to prove your identity in one go, as well, and not needing you to find your NSW Digital Driver Licence app to get your identity displayed.

Why can't smartphones do that? Why can't it integrate all the services its apps can provide?
The problem isn't specific to smartphone. In fact, the web works that way too. The only place where the web is more or less integrated is your inbox, but even that is barely integrated. For example, for an email "a package is available for pick up", you wouldn't know if you already picked it up since an email can't be updated.

The web is modelled after a conversation model - you go to a website first, then converse with that website. Smartphones simply inherited the model. But the web didn't market itself being smart - it is marked as being "connected". So today's smartphone is just as smart as the web. It should be called "ConnectedPhone" really.

When the web was designed, the prevailing thinking is the "Computer-Human interaction" model, where a computer tries to have a conversation with a human. The web, which allows millions of computers to be networked, extended that model in a model I call "cocktail party conversation": you can have a conversation with any computer in the party, and if they mention something that only another computer knows, you can walk to that computer and start a new conversation.

This is how the web was built. You can access a website. Everything on that website is from, er, that website, until you decide to follow a link to a different website. Like moving to another cocktail party guest, you walk to the new website and talk.

On today's smartphones, each app is like a website. Although each of them provides mobile-friendly functions, like rotating screen and notifications, each one is on its own. They are like The Smurfs - each one is a little helper, but your mobile phone is like the Smurf village. When you use a smartphone, it's more like a window to access each Smurf one at a time than a smart personal assistant. In reality, it's not smarter than the web. The web is about "connected", what smartphone is about? Smartness?
Google is more aware of this problem in this area. It tried to provide a "unified front" of services through Google Assistant. If you ask how to go to the nearest hospital, it gives not only the destination but also the means to get there: 30 minutes if you drive, 34 minutes if you use a Uber driver at $30.
Google's way of solving this problem has two serious limitations - it can't provide a service without having access to the user's sensitive information, and it can't be easily extended.

**Comment by James-Sangalli** [comment] 2019-03-03 04:34
@colourful-land my scorn has paid off, this version is much better! We should use something like this for medium articles and reference the actual paper at the bottom

**Comment by colourful-land** [comment] 2019-03-21 00:28
The people decided against you. Feedback from @zhangzhongnan928 and @theBergmann and @hboon didn't mention the smartphone story at all. Currently, the first title gets the most vote (2 votes, @theBergmann  and @zhangzhongnan928 ) so I'll write that one into a TL;DR article then I'll close this issue.

**Closed** 2019-05-12 05:38 UTC
Labels: feedbacks
