### ISSUE TITLE
Assume all JS is wrapped in CDATA

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#339] opened 2020-04-17 04:12 UTC
TokenScripts like ENS require libraries to be bundled together. 

The CDATA tag set in the base js file does not wrap around the whole JS when it is bundled, this should not happen.

**Comment by colourful-land** [comment] 2020-04-17 08:04
Depends on `Manifest` support (the inclusion of resources of different mime type than XML)

**Comment by colourful-land** [comment] 2020-04-17 08:04
Duplicate of https://github.com/AlphaWallet/TokenScript/issues/300

**Closed by colourful-land** 2020-04-17 08:04 UTC
