### ISSUE TITLE
make mapping implied by the existance of <mapping>; move <mapping> inside each origin

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#127] opened 2019-05-02 05:39 UTC
Boon, [02.05.19 15:16]
````
<ts:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7" as="mapping"> <!-- boolean -->
  <ts:origins>
    <ts:ethereum contract="EntryToken" function="isExpired">
      <ts:inputs><ts:uint256 ref="tokenID"/></ts:inputs>
    </ts:ethereum>
  </ts:origins>
  <ts:mapping>
    <ts:option key="0"><ts:value>FALSE</ts:value></ts:option>
    <ts:option key="1"><ts:value>TRUE</ts:value></ts:option>
  </ts:mapping>
</ts:attribute-type>
````
New proposal:

````
<ts:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7"> <!-- boolean -->
<ts:origins>
   <ts:ethereum contract="EntryToken" function="isExpired" as="uint">
     <ts:inputs><ts:uint256 ref="tokenID"/></ts:inputs>
   <ts:mapping>
     <ts:option key="0"><ts:value>FALSE</ts:value></ts:option>
     <ts:option key="1"><ts:value>TRUE</ts:value></ts:option>
   </ts:mapping>
  </ts:ethereum>
</ts:origins>
</ts:attribute-type>
````

Rationale: For 5 types of origins:

- Smart Contract (include both return value and event);
- Token ID;
- Attestation;
- Trusted https;
- user-entry

It's reasonable to expect that for the same attribute-type, some origins use mapping and some do not.

**Comment by hboon** [comment] 2019-05-02 06:13
1. If the issue is that the variety of types are limited, TokenScript can also define builtin types/mappings which auto converts.
2. I happened to pick the example which is type boolean (syntax="1.3.6.1.4.1.1466.115.121.1.7") above because it's available and written with a mapping. But if the smart contract function used by the origin already returns a `bool`, we don't need a mapping.

**Comment by hboon** [comment] 2019-05-03 02:25
Could have sworn I have assigned this to you when I created it. Oh well.

**Comment by colourful-land** [comment] 2019-05-06 01:56
> 1. If the issue is that the variety of types are limited, TokenScript can also define builtin types/mappings which auto converts.

You are right. Mapping is more suitable for fields like `venue`

> 2. I happened to pick the example which is type boolean (syntax="1.3.6.1.4.1.1466.115.121.1.7") above because it's available and written with a mapping. But if the smart contract function used by the origin already returns a `bool`, we don't need a mapping.

You are right. We could use an `as="bool"` instead.

Here is what I propose `as` to mean, taking in all of your 3 pieces of advice (the 3rd being as="mapping" can be dropped because 𝑎) we need to indicate the key format and 𝑏) mapping is evident)

`as` represent the data type to expect from the origin. It is needed for different reasons by different origins.

- for ethereum functions, because the return value of a smart function call is untyped, and we use `as` to anticipate a type.
- for user's entry, because it is always a string, we need to convert it to a type, applying some conversion rules as needed, e.g. `e18`

**Closed** 2019-05-08 08:45 UTC
Labels: schema
